#ifndef METAFUN_METAFUNCTIONSPCH_HPP
#define METAFUN_METAFUNCTIONSPCH_HPP

#include <algorithm>
#include <any>
#include <array>
#include <bit>
#include <cassert>
#include <chrono>
#include <compare>
#include <coroutine>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <deque>
#include <functional>
#include <iostream>
#include <list>
#include <memory>
#include <numeric>
#include <optional>
#include <ranges>
#include <span>
#include <string_view>
#include <type_traits>
#include <utility>
#include <variant>
#include <vector>
#endif//METAFUN_METAFUNCTIONSPCH_HPP
